php artisan make:model User
php artisan make:model Hotel
php artisan make:model RoomType
php artisan make:model Price
php artisan make:model Booking
php artisan make:model BookingRoom
php artisan make:model Payment
php artisan make:model Service
php artisan make:model ServiceRoom
php artisan make:model PlanPrice
php artisan make:model PercentagePerBooking
php artisan make:model Rating
